// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wudallwmrmabiopjuwiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZGFsbHdtcm1hYmlvcGp1d2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjMyOTgsImV4cCI6MjA1Mjc5OTI5OH0.4e0HohR6_OHGMgGhFPMez0bOKUo8g_FDv7cAELQnQiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);